### ISSUE TITLE
admin bar...

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-file-page-cache#1]
the admin bar show up even on device not loggued too.

like i have 2 website where your plugin are running.

everything seems to be fine, but when i check on a private session of chrome on one of the website it show the admin bar.

i check on safari mobile, ie, firefox and the admin bar is there, like it shouldn't be there on browser i decide not to log too.

**Comment by optimalisatie** [comment]
Hi Maxime,

Thank you for reporting the bug!

The issue has been resolved in `0.0.7`.
