### ISSUE TITLE
Cache doesn't flush when updating Post

### ISSUE THREAD

**Issue by felitsche** [o10n-x/wordpress-file-page-cache#12]
When I update a post (manually in Wordpress or with $my_post['post_modified'] / $my_post['post_modified_gmt'] ), my visitors still see the old (cached) version of the post.

Is there a possibility to flush or re-create the cache only for the updated posts?

**Comment by optimalisatie** [comment]
HI @felitsche,

The option to clear the cache from the post editor has been added in `v0.0.40`.

https://github.com/o10n-x/wordpress-file-page-cache/releases

We've added a new innovation that enables to clear the cache using the key combination `Ctrl-Shift-R` in most browsers. This makes it more easy to test when making changes to the HTML.

## Quick Clear Cache using `Ctrl-Shift-R`

The following example shows a trick to clear the cache of a page using `Crtrl-Shift-R`, an option in most browsers to bypass the browser cache. The code in the example can be enabled by first setting a secret cookie via the browser console.

#### Example: set secret cookie (via browser console):

```javascript
document.cookie = "secrect-cookie-cache-admin=secret-code; expires= Thu, 21 Aug 2022 20:00:00 UTC ;domain=domain.com"
```

#### wp-config.php

```php
// bypass advanced cache (wp-content/advanced-cache.php) to allow functions.php to provoke cache clear method
if (isset($_COOKIE['secrect-cookie-cache-admin']) && intval($_COOKIE['secrect-cookie-cache-admin']) === 'secret-code' && isset($_SERVER['HTTP_PRAGMA']) && $_SERVER['HTTP_PRAGMA'] === 'no-cache') {
    define('O10N_BYPASS_ADVANCED_CACHE', true);
}
```

#### functions.php

```php
// clear cache for current page when forcing cache-bypass in the browser (Ctrl-Shift-R, HTTP header pragma:no-cache)
if (isset($_COOKIE['secrect-cookie-cache-admin']) && intval($_COOKIE['secrect-cookie-cache-admin']) === 'secret-code' && isset($_SERVER['HTTP_PRAGMA']) && $_SERVER['HTTP_PRAGMA'] === 'no-cache' && function_exists('O10n\page_cache_clear')) {
    \O10n\page_cache_clear(); // clear cache for current page
}
```

The above code enables to quickly clear the page cache for a page by pressing `Crtrl-Shift-R` in the browser while in the same time the browser cache is bypassed.
