### ISSUE TITLE
on publish it do not clear the cache or the frontpage cache

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-file-page-cache#3]
i add like 5 articles on my website and i had to hit multiple time the flush cache button it didn't empty by itself.

**Comment by optimalisatie** [comment]
Hi Maxime,

Could it be that a Service Worker cache was still serving pages from cache? 

If the cache is flushed, the cache files will be deleted.

**Comment by mxmkmarquette** [comment]
it have been corrected over the version you can closed this thread.
