### ISSUE TITLE
Make the plugin add.

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-file-page-cache#4]
make the plugin add 

`define('WP_CACHE', true);`

i don't know if it's a good idea or if it's link, but i was using your plugin everything were fine, but then i saw in my wp-config.php that it didn't had the wp_cache and the minute i activate it, bang just amazing true speed and else.

**Comment by optimalisatie** [comment]
Hi Maxime,

Thank you very much for the suggestion!

The plugin has been updated with many new features and now supports `advanced-cache.php`. Together with PHP Opcache mode, this enables zero file IO caching (full memory cache with no serialization overhead). It will result in the fastest cache possible in PHP.

https://github.com/o10n-x/wordpress-file-page-cache/releases/tag/0.0.12
