### ISSUE TITLE
hi i got this error

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-file-page-cache#5]
```
<br />
<b>Fatal error</b>:  Cannot declare class O10n\Filecache_Output, because the name is already in use in <b>/srv/users/serverpilot/apps/madmax/public/wp-content/plugins/wordpress-file-page-cache/output-cache.php</b> on line <b>15</b><br />
```
it's telling me this here.
https://max-mad.com/produit/coton-ouate-madmax-blanc

and for some reason the cache do not refresh at this place.

**Comment by optimalisatie** [comment]
Thank you for reporting the issue!

The issue should be fixed in `v0.0.15`.

https://github.com/o10n-x/wordpress-file-page-cache/releases/tag/0.0.15
