### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-file-page-cache#8]
Hi i dig into the .json but either i'm not that familiar with json and else or i didn't find what i was looking.

when i use the preload option with like a delay of like let's say 180

Failed to save settings. The input contains the following errors.

filecache The property preload is not defined and the definition does not allow additional properties

that's my setting maybe i do something bad i hope you gonna be able to help me.

![image](https://user-images.githubusercontent.com/21690761/40647799-c774a28e-62fa-11e8-9dfe-f14c44cbf734.png)

**Comment by optimalisatie** [comment]
Hi @mxmkmarquette

Could you please try again with the latest version `v0.0.40`?

https://github.com/o10n-x/wordpress-file-page-cache/releases
