### ISSUE TITLE
Front Page seems to ignore cache bypass

### ISSUE THREAD

**Issue by BenBrocka** [o10n-x/wordpress-file-page-cache#9]
Version 0.0.25
When using the file cache even with no options turned on by the cache itself, the front page always servers a logged-out cache. All other pages appear unaffected. Front page also seems to expire incorrectly, always had to manually clear the cache to get it to update in testing; an issue would break CSS, which was corrected then all other pages show fine but the front page would always show the error.

Page says advanced-cache.php is installed successfully.

**Comment by optimalisatie** [comment]
Hi @BenBrocka,

The issue has been resolved in recent updates. The latest version is `v0.0.40`.

https://github.com/o10n-x/wordpress-file-page-cache/releases
